# Generated by Django 3.2.25 on 2024-11-21 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import help.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=help.models.help_image_file_path)),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('modify_dt', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
