services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./recipick_app:/recipick_app
      - rp-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=rpdb
      - DB_USER=rpteam
      - DB_PASS=passkey
      - SECRET_KEY=secretkey
      - REDIS_HOST=redis
      - CORS_ALLOWED_ORIGINS=http://localhost:8080
      - DEBUG=1
      - RUNPOD_API_URL=${RUNPOD_API_URL}
      - RUNPOD_API_KEY=${RUNPOD_API_KEY}
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13-alpine
    volumes:
      - rp-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rpdb
      - POSTGRES_USER=rpteam
      - POSTGRES_PASSWORD=passkey

volumes:
  rp-db-data:
  rp-static-data:
  huggingface-cache: