# Generated by Django 3.2.25 on 2024-11-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20241117_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
