# Generated by Django 3.2.25 on 2024-11-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='user',
        ),
        migrations.DeleteModel(
            name='FreeMarket',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
