# Generated by Django 3.2.25 on 2024-11-21 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lab.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0011_alter_ingredient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=lab.models.lab_image_file_path)),
                ('description', models.TextField()),
                ('create_dt', models.DateField(auto_now_add=True)),
                ('modify_dt', models.DateField(auto_now=True)),
                ('ingredients', models.ManyToManyField(to='recipe.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lablikes', to='lab.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lablikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
