# Generated by Django 3.2.25 on 2024-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_level_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
