# Generated by Django 3.2.25 on 2024-11-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_report_reportpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reportpage',
        ),
    ]
