# Generated by Django 3.2.25 on 2024-11-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_loc'),
        ('core', '0005_delete_reportpage'),
    ]

    operations = [
    ]
