# Generated by Django 3.2.25 on 2024-11-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0003_alter_user_loc_0005_delete_reportpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(default='초보요리사', max_length=20, unique=True),
        ),
    ]
