# Generated by Django 3.2.25 on 2024-11-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20241118_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.status'),
        ),
        migrations.DeleteModel(
            name='Reportpage',
        ),
    ]
