# Generated by Django 3.2.25 on 2024-12-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20241119_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='url',
            field=models.URLField(),
        ),
    ]
