# Generated by Django 3.2.25 on 2024-11-22 04:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freemarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='freemark',
            new_name='Freemarket',
        ),
    ]
